// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx_ZBkoTaxcioUbw6MAn_wdPc2Q6bti0Q',
    appId: '1:747261955655:web:05396e789650d8b99eab62',
    messagingSenderId: '747261955655',
    projectId: 'purduedash-50f0b',
    authDomain: 'purduedash-50f0b.firebaseapp.com',
    storageBucket: 'purduedash-50f0b.appspot.com',
    measurementId: 'G-7ZST7NGTD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlVaUrWIYNPAkQb-zttHqM40_mdUBMK2k',
    appId: '1:747261955655:android:6a8777a3e9b4e9629eab62',
    messagingSenderId: '747261955655',
    projectId: 'purduedash-50f0b',
    storageBucket: 'purduedash-50f0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy8D2E14Ld3xRJeiTNuY9ZBYALdp1nDIw',
    appId: '1:747261955655:ios:34119d18d47116089eab62',
    messagingSenderId: '747261955655',
    projectId: 'purduedash-50f0b',
    storageBucket: 'purduedash-50f0b.appspot.com',
    iosBundleId: 'com.example.purdueDashCourierApp',
  );
}
